services:
  app:
    build: .
    container_name: zorvyn-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://root:password@postgres:5432/zorvyn_baas
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - postgres
      - migrate
    volumes:
      - ./logs:/app/logs
    command: >
      sh -c "
        echo 'Waiting for DB...';
        until nc -z postgres 5432; do sleep 2; done;
        echo 'Seeding DB...';
        pnpm db:seed &&
        echo 'Starting server...';
        pnpm start
      "
  migrate:
    build: .
    command: pnpm db:migrate
    environment:
      - DATABASE_URL=postgres://root:password@postgres:5432/zorvyn_baas
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: zorvyn-postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/db/postgres/scripts/001_initialization.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data: